import re
import io
import html as html_lib
from uuid import uuid4
from pathlib import Path

import streamlit as st
from google import genai
from google.genai import types
import PIL.Image

# ── Page config (must be first Streamlit call) ───────────────────────────────
st.set_page_config(
    page_title="Ghost Architect",
    page_icon="👻",
    layout="wide",
    initial_sidebar_state="expanded",
)

MIN_REQUIRED_IMAGES = 3
MAX_RECOMMENDED_IMAGES = 6
UNIVERSAL_BACKEND_ASSUMPTIONS = (
    "Universal backend assumptions (apply unless already present or strongly contradictory):\n"
    "1. Every table should include a primary key `id` (prefer BIGSERIAL PRIMARY KEY or UUID PRIMARY KEY).\n"
    "2. Every table should include `created_at` and `updated_at` timestamp columns with sensible defaults.\n"
    "3. If login/authentication context is visible (login form, sign-in, auth flow), include "
    "`password_hash` and `auth_token` columns in the user/auth table even if not directly visible.\n"
    "4. Prefer snake_case naming and avoid duplicate semantic columns."
)

SCHEMA_PROMPT = """You are a senior database architect. Analyze ALL uploaded UI screenshots together — they belong to the same web application.

Identify every entity, relationship, and data field visible across ALL screens combined.

Generate a complete, production-ready PostgreSQL schema following these rules:
- Every table MUST have: id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
- Use snake_case for all table names and column names
- Add FK constraints: REFERENCES table_name(id) ON DELETE CASCADE or RESTRICT as contextually appropriate
- Add CREATE INDEX on every FK column
- Add NOT NULL constraints wherever the UI clearly requires a value
- Create junction tables for any many-to-many relationships visible in the UI
- Add COMMENT ON TABLE for each table describing what it stores in plain English

IMPORTANT: Return your response in EXACTLY this format. Nothing before the first ===, nothing after the last line:

=== MERMAID ===
erDiagram
    [complete Mermaid ER diagram with all tables and relationships]
=== SQL ===
-- PostgreSQL Schema generated by Ghost Architect
[complete CREATE TABLE and CREATE INDEX statements]
=== EXPLANATION ===
[2-3 sentences: key design decisions and how you inferred relationships from the UI]"""


# ── Gemini API ────────────────────────────────────────────────────────────────
def _get_client():
    return genai.Client(api_key=st.secrets["GEMINI_API_KEY"])


MODEL_CANDIDATES = ["gemini-3.5-flash", "gemini-2.5-flash"]


def analyze_screenshots(pil_images: list, dialect: str = "PostgreSQL") -> tuple[str, str]:
    """Send images to Gemini with model fallback. Returns (raw_output, model_used)."""
    client = _get_client()
    dialect_note = f"\n\nGenerate schema for {dialect}. Use correct {dialect} syntax and native data types."
    prompt = SCHEMA_PROMPT + dialect_note
    contents = [prompt] + pil_images
    config = types.GenerateContentConfig(temperature=0.1, max_output_tokens=4096)

    last_error = None
    for model_name in MODEL_CANDIDATES:
        try:
            response = client.models.generate_content(
                model=model_name, contents=contents, config=config
            )
            text = response.text
            if not text.strip():
                last_error = ValueError(f"{model_name} returned empty response")
                continue
            if "=== SQL ===" in text or "CREATE TABLE" in text or "=== MERMAID ===" in text:
                return text, model_name
            # Accept any non-empty response as last resort
            return text, model_name
        except Exception as e:
            last_error = e
    raise last_error or RuntimeError("No models available")


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("👻 Ghost Architect")
    st.markdown("**UI → PostgreSQL Schema**")
    st.divider()

    dialect = st.selectbox(
        "Target database dialect",
        ["PostgreSQL", "MySQL 8.0+", "SQLite"],
        index=0,
        help="Changes the SQL syntax and data types in the generated schema."
    )

    st.divider()
    st.markdown("**How it works**")
    st.markdown(
        "1. Upload **3-6 screenshots** from the same product flow\n"
        "2. Include: list/table view + create/edit form + detail/dashboard\n"
        "3. All images sent to Gemini 2.5 Flash in one API call\n"
        "4. Returns consolidated PostgreSQL schema + Mermaid ER diagram"
    )
    st.info(
        "Each session allows 3 analyses. Refresh to reset. "
        "Powered by Gemini 2.5 Flash — free, no GPU needed."
    )


# ── SQL Parser (shared with inference.py) ────────────────────────────────────
def _split_sql_columns(body: str) -> list[str]:
    """Split CREATE TABLE body by top-level commas (keeps DECIMAL(10,2) intact)."""
    parts = []
    current = []
    depth = 0
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth = max(0, depth - 1)
        if ch == "," and depth == 0:
            part = "".join(current).strip()
            if part:
                parts.append(part)
            current = []
            continue
        current.append(ch)
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def parse_create_tables(sql: str) -> list[dict]:
    """Extract CREATE TABLE blocks → list of {name, columns}."""
    tables = []
    pattern = re.compile(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`\"]?(\w+)[`\"]?\s*\((.*?)\)\s*;",
        re.IGNORECASE | re.DOTALL,
    )
    for match in pattern.finditer(sql):
        table_name = match.group(1)
        body = match.group(2)
        columns = []
        for raw_line in _split_sql_columns(body):
            line = raw_line.strip().rstrip(",")
            if not line:
                continue
            if re.match(r"(PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT)\s", line, re.IGNORECASE):
                continue
            parts = line.split()
            if not parts:
                continue
            col_name    = parts[0].strip('`"')
            col_type    = parts[1] if len(parts) > 1 else "?"
            constraints = " ".join(parts[2:]) if len(parts) > 2 else ""
            columns.append({"name": col_name, "type": col_type, "constraints": constraints})
        if columns:
            tables.append({"name": table_name, "columns": columns})
    return tables


def _merge_constraints(existing: str, new: str) -> str:
    existing = existing.strip()
    new = new.strip()
    if not existing:
        return new
    if not new:
        return existing
    merged_tokens = []
    for token in f"{existing} {new}".split():
        if token not in merged_tokens:
            merged_tokens.append(token)
    return " ".join(merged_tokens)


def merge_table_sets(table_sets: list[list[dict]]) -> list[dict]:
    """Merge tables from multiple screenshots into a single consolidated schema.

    NOTE: This is a lightweight fallback parser for rendering visual cards.
    The real "conflict resolution" happens in the Gemini consolidation prompt.
    """
    merged: dict[str, dict] = {}
    for tables in table_sets:
        for table in tables:
            table_key = table["name"].lower()
            if table_key not in merged:
                merged[table_key] = {
                    "name": table["name"],
                    "columns_by_key": {},
                    "column_order": [],
                }
            table_entry = merged[table_key]
            for col in table["columns"]:
                col_key = col["name"].lower()
                existing = table_entry["columns_by_key"].get(col_key)
                if existing is None:
                    table_entry["columns_by_key"][col_key] = {
                        "name": col["name"],
                        "type": col["type"],
                        "constraints": col["constraints"],
                    }
                    table_entry["column_order"].append(col_key)
                    continue

                if existing["type"] in {"?", "TEXT"} and col["type"] not in {"?", "TEXT"}:
                    existing["type"] = col["type"]
                if len(col["constraints"].strip()) > len(existing["constraints"].strip()):
                    existing["constraints"] = col["constraints"]
                else:
                    existing["constraints"] = _merge_constraints(
                        existing["constraints"], col["constraints"]
                    )

    result = []
    for table_key in sorted(merged):
        table_entry = merged[table_key]
        columns = [
            table_entry["columns_by_key"][col_key]
            for col_key in table_entry["column_order"]
        ]
        result.append({"name": table_entry["name"], "columns": columns})
    return result


def _normalize_identifier(name: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9_]+", "_", name.strip().lower())
    return normalized.strip("_") or "unnamed_entity"


def tables_to_sql(tables: list[dict]) -> str:
    """Render merged table representation back into SQL CREATE TABLE statements.

    NOTE: This is a fallback for visual rendering only. The *authoritative* consolidated
    SQL comes from Gemini, not this function.
    """
    statements = []
    for table in tables:
        table_name = _normalize_identifier(table["name"])
        column_lines = []
        for col in table["columns"]:
            col_name = _normalize_identifier(col["name"])
            col_type = col["type"] if col["type"] and col["type"] != "?" else "TEXT"
            constraints = col["constraints"].strip()
            suffix = f" {constraints}" if constraints else ""
            column_lines.append(f"    {col_name} {col_type}{suffix}")
        statements.append(
            f"CREATE TABLE {table_name} (\n" + ",\n".join(column_lines) + "\n);"
        )
    return "\n\n".join(statements)


def _strip_markdown_code_fence(text: str) -> str:
    """Remove optional markdown triple-backtick wrappers."""
    stripped = text.strip()
    fenced = re.match(r"^```[a-zA-Z0-9_+-]*\s*\n(.*?)\n```$", stripped, re.DOTALL)
    if fenced:
        return fenced.group(1).strip()
    return stripped


def split_consolidated_output(raw_output: str) -> dict:
    """
    Parse raw Gemini output into mermaid, sql, and explanation sections.
    Returns dict with keys: mermaid, sql, explanation (each str or None).
    """
    result = {"mermaid": None, "sql": None, "explanation": None}

    has_mermaid = "=== MERMAID ===" in raw_output
    has_sql = "=== SQL ===" in raw_output
    has_explanation = "=== EXPLANATION ===" in raw_output

    if has_mermaid and has_sql:
        mermaid_start = raw_output.find("=== MERMAID ===") + len("=== MERMAID ===")
        mermaid_end = raw_output.find("=== SQL ===")
        result["mermaid"] = _strip_markdown_code_fence(raw_output[mermaid_start:mermaid_end].strip())

    if has_sql:
        sql_start = raw_output.find("=== SQL ===") + len("=== SQL ===")
        sql_end = raw_output.find("=== EXPLANATION ===") if has_explanation else len(raw_output)
        result["sql"] = _strip_markdown_code_fence(raw_output[sql_start:sql_end].strip())

    if has_explanation:
        exp_start = raw_output.find("=== EXPLANATION ===") + len("=== EXPLANATION ===")
        result["explanation"] = raw_output[exp_start:].strip()

    return result


def build_mermaid_html(mermaid_diagram: str, title: str, sql_source: str = "") -> str:
    """Build a polished Mermaid preview HTML with diagram, source blocks, and SQL."""
    safe_title = html_lib.escape(title)
    safe_sql = html_lib.escape(sql_source.strip())
    mermaid_source = _strip_markdown_code_fence(mermaid_diagram).strip()
    safe_mermaid_source = html_lib.escape(mermaid_source)
    diagram_source = safe_mermaid_source or "erDiagram\\n    %% No Mermaid diagram found."

    mermaid_block = f"""
        <details>
          <summary>Show Mermaid source</summary>
          <pre class="source-block">{safe_mermaid_source or "(empty)"}</pre>
        </details>
        """
    sql_block = f"""
        <details>
          <summary>Show SQL statements</summary>
          <pre class="source-block">{safe_sql or "(empty)"}</pre>
        </details>
        """ if safe_sql else ""

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{safe_title}</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f8fafc;
      --panel: #ffffff;
      --border: #dbe4ee;
      --text: #0f172a;
      --muted: #475569;
      --accent: #2563eb;
      --accent-soft: #dbeafe;
    }}
    body {{
      margin: 0;
      background: linear-gradient(180deg, #f8fafc 0%, #eef2ff 100%);
      color: var(--text);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    .page {{
      max-width: 1600px;
      margin: 0 auto;
      padding: 24px;
    }}
    .header {{
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
      margin-bottom: 18px;
    }}
    .title {{
      margin: 0;
      font-size: 24px;
      letter-spacing: -0.02em;
    }}
    .subtitle {{
      margin: 4px 0 0;
      color: var(--muted);
      font-size: 14px;
    }}
    .badge {{
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 8px 12px;
      border: 1px solid var(--border);
      border-radius: 999px;
      background: rgba(255,255,255,0.85);
      font-size: 13px;
      color: var(--muted);
      box-shadow: 0 8px 24px rgba(15, 23, 42, 0.04);
    }}
    .card {{
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 20px;
      box-shadow: 0 18px 50px rgba(15, 23, 42, 0.08);
      overflow: hidden;
    }}
    .card-head {{
      padding: 18px 20px 0;
    }}
    .eyebrow {{
      display: inline-flex;
      align-items: center;
      padding: 6px 10px;
      border-radius: 999px;
      background: var(--accent-soft);
      color: #1d4ed8;
      font-size: 12px;
      font-weight: 800;
      letter-spacing: 0.03em;
      text-transform: uppercase;
    }}
    .description {{
      margin: 10px 0 0;
      color: var(--muted);
      font-size: 14px;
      line-height: 1.5;
    }}
    .diagram-wrap {{
      margin: 18px 20px 0;
      padding: 20px;
      border: 1px solid #cbd5e1;
      border-radius: 18px;
      background: linear-gradient(180deg, #eef2ff 0%, #f8fafc 52%, #e2e8f0 100%);
      overflow: auto;
      min-height: 400px;
    }}
    .diagram-wrap .mermaid {{
      min-width: fit-content;
      width: 100%;
      padding: 16px;
      border-radius: 16px;
      background: linear-gradient(180deg, rgba(255,255,255,0.7) 0%, rgba(248,250,252,0.92) 100%);
    }}
    .diagram-wrap svg {{
      max-width: none !important;
      width: auto !important;
      min-width: 100% !important;
      height: auto !important;
      background: linear-gradient(180deg, #f8fafc 0%, #eef2ff 100%) !important;
      border-radius: 16px;
      box-shadow: inset 0 0 0 1px rgba(148, 163, 184, 0.18);
    }}
    .source-block {{
      margin: 0;
      padding: 16px;
      overflow-x: auto;
      white-space: pre;
      background: #0f172a;
      color: #e2e8f0;
      border: 1px solid #1e293b;
      border-radius: 14px;
      font-size: 13px;
      line-height: 1.55;
    }}
    details {{
      border-top: 1px solid var(--border);
      padding: 16px 20px 18px;
      background: #f8fafc;
    }}
    details summary {{
      cursor: pointer;
      color: var(--accent);
      font-weight: 700;
      margin-bottom: 12px;
    }}
    details pre {{
      margin: 0;
      padding: 16px;
      overflow-x: auto;
      white-space: pre-wrap;
      word-break: break-word;
      background: #0f172a;
      color: #e2e8f0;
      border: 1px solid #1e293b;
      border-radius: 14px;
      font-size: 13px;
      line-height: 1.5;
    }}
    .footer-note {{
      padding: 0 20px 20px;
      color: var(--muted);
      font-size: 13px;
    }}
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div>
        <h1 class="title">{safe_title}</h1>
        <p class="subtitle">Premium Mermaid ER diagram with database relationships.</p>
      </div>
      <div class="badge">Ghost Architect · Gemini 2.5 Flash</div>
    </div>

    <div class="card">
      <div class="card-head">
        <span class="eyebrow">Database Schema</span>
        <p class="description">Visual ER diagram of your inferred PostgreSQL schema</p>
      </div>
      <div class="diagram-wrap">
        <div class="mermaid">
{diagram_source}
        </div>
      </div>
      {mermaid_block}
      {sql_block}
      <div class="footer-note">Copy the SQL statements or use the Mermaid diagram in any renderer.</div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script>
    window.addEventListener('DOMContentLoaded', () => {{
      mermaid.initialize({{
        startOnLoad: false,
        theme: 'base',
        securityLevel: 'loose',
        darkMode: false,
        er: {{
          useMaxWidth: true,
          layoutDirection: 'TB',
          diagramPadding: 40,
          minEntityWidth: 120,
          entityPadding: 20
        }},
        themeVariables: {{
          fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
          fontSize: '16px',
          background: '#eef2ff',
          primaryColor: '#eff6ff',
          primaryTextColor: '#0f172a',
          primaryBorderColor: '#60a5fa',
          secondaryColor: '#f8fafc',
          secondaryTextColor: '#0f172a',
          secondaryBorderColor: '#cbd5e1',
          tertiaryColor: '#ffffff',
          tertiaryTextColor: '#0f172a',
          noteBkgColor: '#ecfeff',
          noteTextColor: '#0f172a',
          noteBorderColor: '#67e8f9',
          lineColor: '#64748b',
          textColor: '#0f172a'
        }}
      }});
      mermaid.run({{ querySelector: '.mermaid' }});
    }});
  </script>
</body>
</html>
"""


def render_schema_cards(tables: list[dict]):
    """Render parsed tables as styled Streamlit columns."""
    if not tables:
        return False

    chunk_size = 3
    for i in range(0, len(tables), chunk_size):
        row_tables = tables[i : i + chunk_size]
        cols = st.columns(len(row_tables))
        for col, table in zip(cols, row_tables):
            with col:
                st.markdown(
                    f"""
                    <div style="
                        background:#1e1e2e;
                        border:1px solid #7c3aed;
                        border-radius:8px;
                        padding:12px;
                        margin-bottom:12px;
                    ">
                    <h4 style="color:#a78bfa;margin:0 0 8px 0;">📋 {table['name']}</h4>
                    """,
                    unsafe_allow_html=True,
                )
                for col_def in table["columns"]:
                    cname = col_def["name"]
                    ctype = col_def["type"]
                    cstr  = col_def["constraints"].upper()

                    if "PRIMARY KEY" in cstr:
                        icon, color = "🔑", "#fbbf24"
                    elif "REFERENCES" in cstr or "FOREIGN" in cstr:
                        icon, color = "🔗", "#60a5fa"
                    elif "NOT NULL" in cstr:
                        icon, color = "●", "#34d399"
                    else:
                        icon, color = "○", "#9ca3af"

                    st.markdown(
                        f"<p style='margin:2px 0;font-size:13px;'>"
                        f"<span style='color:{color}'>{icon}</span> "
                        f"<span style='color:#e2e8f0'>{cname}</span> "
                        f"<span style='color:#64748b'>{ctype}</span>"
                        f"</p>",
                        unsafe_allow_html=True,
                    )
                st.markdown("</div>", unsafe_allow_html=True)
    return True


# ── Custom CSS ──────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .stApp { background: #ffffff; }
    .block-container { max-width: 1400px; padding-top: 1rem; }
    .main-header { text-align: center; padding: 1.5rem 0 0.5rem; }
    .main-header h1 { font-size: 1.8rem; font-weight: 700; color: #111827; margin: 0; }
    .main-header p { color: #6b7280; font-size: 0.9rem; margin: 0.25rem 0 0; }
    .section-title { font-size: 1rem; font-weight: 600; color: #374151; margin-bottom: 0.75rem; }
    [data-testid="stFileUploader"] { border: 1px solid #d1d5db; border-radius: 8px; padding: 0.5rem; }
    [data-testid="stFileUploader"]:hover { border-color: #9ca3af; }
    .stAlert { border-radius: 8px !important; }
    .ghost-footer { text-align: center; padding: 2rem 1rem 1rem; margin-top: 2rem; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 0.8rem; }
    .ghost-footer a { color: #6b7280; text-decoration: none; }
    .ghost-footer a:hover { color: #374151; }
    .ghost-footer .links { display: flex; justify-content: center; gap: 1.5rem; margin-bottom: 0.5rem; flex-wrap: wrap; }
</style>
""", unsafe_allow_html=True)


# ── Main layout ────────────────────────────────────────────────────────────────
st.markdown('<div class="main-header"><h1>👻 Ghost Architect</h1><p>UI screenshots → Database schema + ER Diagram</p></div>', unsafe_allow_html=True)
st.divider()

col_upload, col_schema = st.columns([1, 1], gap="large")

with col_upload:
    st.markdown('<p class="section-title"><strong>1. Upload Screenshots</strong></p>', unsafe_allow_html=True)

    uploaded_files = st.file_uploader(
        "Upload 3-6 PNG/JPG screenshots from the same product",
        type=["png", "jpg", "jpeg"],
        accept_multiple_files=True,
        label_visibility="collapsed",
    )

    if uploaded_files:
        count = len(uploaded_files)
        if count >= MIN_REQUIRED_IMAGES:
            st.success(f"{count} screenshots uploaded")
        else:
            st.warning(f"Need {MIN_REQUIRED_IMAGES - count} more screenshot{'s' if MIN_REQUIRED_IMAGES - count != 1 else ''}")
        if count > MAX_RECOMMENDED_IMAGES:
            st.caption(f"{MAX_RECOMMENDED_IMAGES} is the sweet spot. You can continue with {count}.")

        for f in uploaded_files:
            img = PIL.Image.open(io.BytesIO(f.getvalue())).convert("RGB")
            st.image(img, use_container_width=True)

with col_schema:
    st.markdown('<p class="section-title"><strong>2. Generated Schema</strong></p>', unsafe_allow_html=True)

    if not uploaded_files:
        st.info("Upload screenshots on the left to generate a schema")
    elif len(uploaded_files) < MIN_REQUIRED_IMAGES:
        st.info(f"Upload {MIN_REQUIRED_IMAGES - len(uploaded_files)} more screenshot{'s' if MIN_REQUIRED_IMAGES - len(uploaded_files) != 1 else ''} to enable generation")
    else:
        generate_btn = st.button("Generate Schema", type="primary", use_container_width=True)

        if generate_btn:
            if "request_count" not in st.session_state:
                st.session_state.request_count = 0
            if st.session_state.request_count >= 3:
                st.warning("You've used 3 free analyses this session. Refresh to continue.")
                st.stop()

            pil_images = []
            for f in uploaded_files:
                img = PIL.Image.open(io.BytesIO(f.getvalue()))
                if img.mode != "RGB":
                    img = img.convert("RGB")
                pil_images.append(img)

            with st.spinner("Analyzing screenshots..."):
                try:
                    raw_output, model_used = analyze_screenshots(pil_images, dialect)
                    st.session_state.request_count += 1
                except Exception as e:
                    err_str = str(e)
                    if "API_KEY_INVALID" in err_str or "PERMISSION_DENIED" in err_str or "UNAUTHENTICATED" in err_str:
                        st.error("Gemini API key is invalid or expired. Admin must update it.")
                    elif "429" in err_str or "RESOURCE_EXHAUSTED" in err_str:
                        st.error("API rate limit reached. Wait a moment and try again.")
                    elif "503" in err_str or "UNAVAILABLE" in err_str:
                        st.error("Gemini service is temporarily unavailable. Try again in a few seconds.")
                    else:
                        st.error(f"Analysis failed: {err_str}")
                    st.stop()

            parsed = split_consolidated_output(raw_output)
            st.caption(f"Generated by {model_used} · {len(uploaded_files)} screenshots")

            if parsed["explanation"]:
                st.info(parsed["explanation"])

            tab_vis, tab_sql = st.tabs(["ER Diagram", "SQL Schema"])

            with tab_vis:
                if parsed["mermaid"]:
                    st.components.v1.html(
                        build_mermaid_html(parsed["mermaid"], "Ghost Architect: Database Schema", parsed["sql"] or ""),
                        height=900, scrolling=True,
                    )
                elif parsed["sql"]:
                    parsed_tables = parse_create_tables(parsed["sql"])
                    if parsed_tables:
                        render_schema_cards(parsed_tables)
                    st.info("Mermaid diagram not available.")
                else:
                    st.code(raw_output, language="text")

            with tab_sql:
                if parsed["sql"]:
                    st.code(parsed["sql"], language="sql")
                else:
                    st.code(raw_output, language="text")

            if parsed["sql"] or parsed["mermaid"]:
                st.markdown("---")
                dl_col1, dl_col2, dl_col3 = st.columns(3)
                if parsed["sql"]:
                    dl_col1.download_button("Download SQL", data=parsed["sql"], file_name="ghost_architect_schema.sql", mime="text/plain", use_container_width=True)
                if parsed["mermaid"]:
                    dl_col2.download_button("Download Mermaid", data=parsed["mermaid"], file_name="ghost_architect_schema.mmd", mime="text/plain", use_container_width=True)
                if parsed["sql"] and parsed["mermaid"]:
                    report = f"# Ghost Architect — Database Schema\n\n## Design Decisions\n{parsed.get('explanation', 'N/A')}\n\n## ER Diagram\n```mermaid\n{parsed['mermaid']}\n```\n\n## DDL\n```sql\n{parsed['sql']}\n```\n"
                    dl_col3.download_button("Download Report (.md)", data=report, file_name="ghost_architect_schema_report.md", mime="text/markdown", use_container_width=True)

            if not parsed["mermaid"] and not parsed["sql"]:
                parsed_tables = parse_create_tables(raw_output)
                if parsed_tables:
                    render_schema_cards(parsed_tables)


# ── Footer ─────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="ghost-footer">
    <div class="links">
        <a href="https://github.com/HarshilMaks/ghost_architect_gemma3">GitHub</a>
        <a href="https://huggingface.co/harshilmaks/ghost-architect-gemma3-adapter">HuggingFace</a>
        <a href="https://aistudio.google.com">Gemini API</a>
    </div>
    <p>Ghost Architect · Apache 2.0</p>
</div>
""", unsafe_allow_html=True)
