import re
import io
import html as html_lib
from uuid import uuid4
from pathlib import Path

import streamlit as st
from google import genai
from google.genai import types
import PIL.Image

# ── Page config (must be first Streamlit call) ───────────────────────────────
st.set_page_config(
    page_title="Ghost Architect",
    page_icon="👻",
    layout="wide",
    initial_sidebar_state="expanded",
)

MIN_REQUIRED_IMAGES = 3
MAX_RECOMMENDED_IMAGES = 6
UNIVERSAL_BACKEND_ASSUMPTIONS = (
    "Universal backend assumptions (apply unless already present or strongly contradictory):\n"
    "1. Every table should include a primary key `id` (prefer BIGSERIAL PRIMARY KEY or UUID PRIMARY KEY).\n"
    "2. Every table should include `created_at` and `updated_at` timestamp columns with sensible defaults.\n"
    "3. If login/authentication context is visible (login form, sign-in, auth flow), include "
    "`password_hash` and `auth_token` columns in the user/auth table even if not directly visible.\n"
    "4. Prefer snake_case naming and avoid duplicate semantic columns."
)

SCHEMA_PROMPT = """You are a senior database architect. Analyze ALL uploaded UI screenshots together — they belong to the same web application.

Identify every entity, relationship, and data field visible across ALL screens combined.

Generate a complete, production-ready PostgreSQL schema following these rules:
- Every table MUST have: id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
- Use snake_case for all table names and column names
- Add FK constraints: REFERENCES table_name(id) ON DELETE CASCADE or RESTRICT as contextually appropriate
- Add CREATE INDEX on every FK column
- Add NOT NULL constraints wherever the UI clearly requires a value
- Create junction tables for any many-to-many relationships visible in the UI
- Add COMMENT ON TABLE for each table describing what it stores in plain English

IMPORTANT: Return your response in EXACTLY this format. Nothing before the first ===, nothing after the last line:

=== MERMAID ===
erDiagram
    [complete Mermaid ER diagram with all tables and relationships]
=== SQL ===
-- PostgreSQL Schema generated by Ghost Architect
[complete CREATE TABLE and CREATE INDEX statements]
=== EXPLANATION ===
[2-3 sentences: key design decisions and how you inferred relationships from the UI]"""


# ── Gemini API ────────────────────────────────────────────────────────────────
def _get_client():
    return genai.Client(api_key=st.secrets["GEMINI_API_KEY"])


MODEL_CANDIDATES = ["gemini-3.5-flash", "gemini-2.5-flash"]


def analyze_screenshots(pil_images: list, dialect: str = "PostgreSQL") -> tuple[str, str]:
    """Send images to Gemini with model fallback. Returns (raw_output, model_used)."""
    client = _get_client()
    dialect_note = f"\n\nGenerate schema for {dialect}. Use correct {dialect} syntax and native data types."
    prompt = SCHEMA_PROMPT + dialect_note
    contents = [prompt] + pil_images
    config = types.GenerateContentConfig(temperature=0.1, max_output_tokens=4096)

    last_error = None
    for model_name in MODEL_CANDIDATES:
        try:
            response = client.models.generate_content(
                model=model_name, contents=contents, config=config
            )
            if "=== SQL ===" in response.text:
                return response.text, model_name
            last_error = ValueError(f"{model_name} ignored the output format")
        except Exception as e:
            last_error = e
    raise last_error or RuntimeError("No models available")


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("👻 Ghost Architect")
    st.markdown("**UI → PostgreSQL Schema**")
    st.divider()

    dialect = st.selectbox(
        "Target database dialect",
        ["PostgreSQL", "MySQL 8.0+", "SQLite"],
        index=0,
        help="Changes the SQL syntax and data types in the generated schema."
    )

    st.divider()
    st.markdown("**How it works**")
    st.markdown(
        "1. Upload **3-6 screenshots** from the same product flow\n"
        "2. Include: list/table view + create/edit form + detail/dashboard\n"
        "3. All images sent to Gemini 2.5 Flash in one API call\n"
        "4. Returns consolidated PostgreSQL schema + Mermaid ER diagram"
    )
    st.info(
        "Each session allows 3 analyses. Refresh to reset. "
        "Powered by Gemini 2.5 Flash — free, no GPU needed."
    )


# ── SQL Parser (shared with inference.py) ────────────────────────────────────
def _split_sql_columns(body: str) -> list[str]:
    """Split CREATE TABLE body by top-level commas (keeps DECIMAL(10,2) intact)."""
    parts = []
    current = []
    depth = 0
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth = max(0, depth - 1)
        if ch == "," and depth == 0:
            part = "".join(current).strip()
            if part:
                parts.append(part)
            current = []
            continue
        current.append(ch)
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def parse_create_tables(sql: str) -> list[dict]:
    """Extract CREATE TABLE blocks → list of {name, columns}."""
    tables = []
    pattern = re.compile(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`\"]?(\w+)[`\"]?\s*\((.*?)\)\s*;",
        re.IGNORECASE | re.DOTALL,
    )
    for match in pattern.finditer(sql):
        table_name = match.group(1)
        body = match.group(2)
        columns = []
        for raw_line in _split_sql_columns(body):
            line = raw_line.strip().rstrip(",")
            if not line:
                continue
            if re.match(r"(PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT)\s", line, re.IGNORECASE):
                continue
            parts = line.split()
            if not parts:
                continue
            col_name    = parts[0].strip('`"')
            col_type    = parts[1] if len(parts) > 1 else "?"
            constraints = " ".join(parts[2:]) if len(parts) > 2 else ""
            columns.append({"name": col_name, "type": col_type, "constraints": constraints})
        if columns:
            tables.append({"name": table_name, "columns": columns})
    return tables


def _merge_constraints(existing: str, new: str) -> str:
    existing = existing.strip()
    new = new.strip()
    if not existing:
        return new
    if not new:
        return existing
    merged_tokens = []
    for token in f"{existing} {new}".split():
        if token not in merged_tokens:
            merged_tokens.append(token)
    return " ".join(merged_tokens)


def merge_table_sets(table_sets: list[list[dict]]) -> list[dict]:
    """Merge tables from multiple screenshots into a single consolidated schema.

    NOTE: This is a lightweight fallback parser for rendering visual cards.
    The real "conflict resolution" happens in the Gemini consolidation prompt.
    """
    merged: dict[str, dict] = {}
    for tables in table_sets:
        for table in tables:
            table_key = table["name"].lower()
            if table_key not in merged:
                merged[table_key] = {
                    "name": table["name"],
                    "columns_by_key": {},
                    "column_order": [],
                }
            table_entry = merged[table_key]
            for col in table["columns"]:
                col_key = col["name"].lower()
                existing = table_entry["columns_by_key"].get(col_key)
                if existing is None:
                    table_entry["columns_by_key"][col_key] = {
                        "name": col["name"],
                        "type": col["type"],
                        "constraints": col["constraints"],
                    }
                    table_entry["column_order"].append(col_key)
                    continue

                if existing["type"] in {"?", "TEXT"} and col["type"] not in {"?", "TEXT"}:
                    existing["type"] = col["type"]
                if len(col["constraints"].strip()) > len(existing["constraints"].strip()):
                    existing["constraints"] = col["constraints"]
                else:
                    existing["constraints"] = _merge_constraints(
                        existing["constraints"], col["constraints"]
                    )

    result = []
    for table_key in sorted(merged):
        table_entry = merged[table_key]
        columns = [
            table_entry["columns_by_key"][col_key]
            for col_key in table_entry["column_order"]
        ]
        result.append({"name": table_entry["name"], "columns": columns})
    return result


def _normalize_identifier(name: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9_]+", "_", name.strip().lower())
    return normalized.strip("_") or "unnamed_entity"


def tables_to_sql(tables: list[dict]) -> str:
    """Render merged table representation back into SQL CREATE TABLE statements.

    NOTE: This is a fallback for visual rendering only. The *authoritative* consolidated
    SQL comes from Gemini, not this function.
    """
    statements = []
    for table in tables:
        table_name = _normalize_identifier(table["name"])
        column_lines = []
        for col in table["columns"]:
            col_name = _normalize_identifier(col["name"])
            col_type = col["type"] if col["type"] and col["type"] != "?" else "TEXT"
            constraints = col["constraints"].strip()
            suffix = f" {constraints}" if constraints else ""
            column_lines.append(f"    {col_name} {col_type}{suffix}")
        statements.append(
            f"CREATE TABLE {table_name} (\n" + ",\n".join(column_lines) + "\n);"
        )
    return "\n\n".join(statements)


def _strip_markdown_code_fence(text: str) -> str:
    """Remove optional markdown triple-backtick wrappers."""
    stripped = text.strip()
    fenced = re.match(r"^```[a-zA-Z0-9_+-]*\s*\n(.*?)\n```$", stripped, re.DOTALL)
    if fenced:
        return fenced.group(1).strip()
    return stripped


def split_consolidated_output(raw_output: str) -> dict:
    """
    Parse raw Gemini output into mermaid, sql, and explanation sections.
    Returns dict with keys: mermaid, sql, explanation (each str or None).
    """
    result = {"mermaid": None, "sql": None, "explanation": None}

    has_mermaid = "=== MERMAID ===" in raw_output
    has_sql = "=== SQL ===" in raw_output
    has_explanation = "=== EXPLANATION ===" in raw_output

    if has_mermaid and has_sql:
        mermaid_start = raw_output.find("=== MERMAID ===") + len("=== MERMAID ===")
        mermaid_end = raw_output.find("=== SQL ===")
        result["mermaid"] = _strip_markdown_code_fence(raw_output[mermaid_start:mermaid_end].strip())

    if has_sql:
        sql_start = raw_output.find("=== SQL ===") + len("=== SQL ===")
        sql_end = raw_output.find("=== EXPLANATION ===") if has_explanation else len(raw_output)
        result["sql"] = _strip_markdown_code_fence(raw_output[sql_start:sql_end].strip())

    if has_explanation:
        exp_start = raw_output.find("=== EXPLANATION ===") + len("=== EXPLANATION ===")
        result["explanation"] = raw_output[exp_start:].strip()

    return result


def build_mermaid_html(mermaid_diagram: str, title: str, sql_source: str = "") -> str:
    """Build a polished Mermaid preview HTML with diagram, source blocks, and SQL."""
    safe_title = html_lib.escape(title)
    safe_sql = html_lib.escape(sql_source.strip())
    mermaid_source = _strip_markdown_code_fence(mermaid_diagram).strip()
    safe_mermaid_source = html_lib.escape(mermaid_source)
    diagram_source = safe_mermaid_source or "erDiagram\\n    %% No Mermaid diagram found."

    mermaid_block = f"""
        <details>
          <summary>Show Mermaid source</summary>
          <pre class="source-block">{safe_mermaid_source or "(empty)"}</pre>
        </details>
        """
    sql_block = f"""
        <details>
          <summary>Show SQL statements</summary>
          <pre class="source-block">{safe_sql or "(empty)"}</pre>
        </details>
        """ if safe_sql else ""

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{safe_title}</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f8fafc;
      --panel: #ffffff;
      --border: #dbe4ee;
      --text: #0f172a;
      --muted: #475569;
      --accent: #2563eb;
      --accent-soft: #dbeafe;
    }}
    body {{
      margin: 0;
      background: linear-gradient(180deg, #f8fafc 0%, #eef2ff 100%);
      color: var(--text);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    .page {{
      max-width: 1600px;
      margin: 0 auto;
      padding: 24px;
    }}
    .header {{
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
      margin-bottom: 18px;
    }}
    .title {{
      margin: 0;
      font-size: 24px;
      letter-spacing: -0.02em;
    }}
    .subtitle {{
      margin: 4px 0 0;
      color: var(--muted);
      font-size: 14px;
    }}
    .badge {{
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 8px 12px;
      border: 1px solid var(--border);
      border-radius: 999px;
      background: rgba(255,255,255,0.85);
      font-size: 13px;
      color: var(--muted);
      box-shadow: 0 8px 24px rgba(15, 23, 42, 0.04);
    }}
    .card {{
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 20px;
      box-shadow: 0 18px 50px rgba(15, 23, 42, 0.08);
      overflow: hidden;
    }}
    .card-head {{
      padding: 18px 20px 0;
    }}
    .eyebrow {{
      display: inline-flex;
      align-items: center;
      padding: 6px 10px;
      border-radius: 999px;
      background: var(--accent-soft);
      color: #1d4ed8;
      font-size: 12px;
      font-weight: 800;
      letter-spacing: 0.03em;
      text-transform: uppercase;
    }}
    .description {{
      margin: 10px 0 0;
      color: var(--muted);
      font-size: 14px;
      line-height: 1.5;
    }}
    .diagram-wrap {{
      margin: 18px 20px 0;
      padding: 20px;
      border: 1px solid #cbd5e1;
      border-radius: 18px;
      background: linear-gradient(180deg, #eef2ff 0%, #f8fafc 52%, #e2e8f0 100%);
      overflow: auto;
      min-height: 400px;
    }}
    .diagram-wrap .mermaid {{
      min-width: fit-content;
      width: 100%;
      padding: 16px;
      border-radius: 16px;
      background: linear-gradient(180deg, rgba(255,255,255,0.7) 0%, rgba(248,250,252,0.92) 100%);
    }}
    .diagram-wrap svg {{
      max-width: none !important;
      width: auto !important;
      min-width: 100% !important;
      height: auto !important;
      background: linear-gradient(180deg, #f8fafc 0%, #eef2ff 100%) !important;
      border-radius: 16px;
      box-shadow: inset 0 0 0 1px rgba(148, 163, 184, 0.18);
    }}
    .source-block {{
      margin: 0;
      padding: 16px;
      overflow-x: auto;
      white-space: pre;
      background: #0f172a;
      color: #e2e8f0;
      border: 1px solid #1e293b;
      border-radius: 14px;
      font-size: 13px;
      line-height: 1.55;
    }}
    details {{
      border-top: 1px solid var(--border);
      padding: 16px 20px 18px;
      background: #f8fafc;
    }}
    details summary {{
      cursor: pointer;
      color: var(--accent);
      font-weight: 700;
      margin-bottom: 12px;
    }}
    details pre {{
      margin: 0;
      padding: 16px;
      overflow-x: auto;
      white-space: pre-wrap;
      word-break: break-word;
      background: #0f172a;
      color: #e2e8f0;
      border: 1px solid #1e293b;
      border-radius: 14px;
      font-size: 13px;
      line-height: 1.5;
    }}
    .footer-note {{
      padding: 0 20px 20px;
      color: var(--muted);
      font-size: 13px;
    }}
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div>
        <h1 class="title">{safe_title}</h1>
        <p class="subtitle">Premium Mermaid ER diagram with database relationships.</p>
      </div>
      <div class="badge">Ghost Architect · Gemini 2.5 Flash</div>
    </div>

    <div class="card">
      <div class="card-head">
        <span class="eyebrow">Database Schema</span>
        <p class="description">Visual ER diagram of your inferred PostgreSQL schema</p>
      </div>
      <div class="diagram-wrap">
        <div class="mermaid">
{diagram_source}
        </div>
      </div>
      {mermaid_block}
      {sql_block}
      <div class="footer-note">Copy the SQL statements or use the Mermaid diagram in any renderer.</div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script>
    window.addEventListener('DOMContentLoaded', () => {{
      mermaid.initialize({{
        startOnLoad: false,
        theme: 'base',
        securityLevel: 'loose',
        darkMode: false,
        er: {{
          useMaxWidth: true,
          layoutDirection: 'TB',
          diagramPadding: 40,
          minEntityWidth: 120,
          entityPadding: 20
        }},
        themeVariables: {{
          fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
          fontSize: '16px',
          background: '#eef2ff',
          primaryColor: '#eff6ff',
          primaryTextColor: '#0f172a',
          primaryBorderColor: '#60a5fa',
          secondaryColor: '#f8fafc',
          secondaryTextColor: '#0f172a',
          secondaryBorderColor: '#cbd5e1',
          tertiaryColor: '#ffffff',
          tertiaryTextColor: '#0f172a',
          noteBkgColor: '#ecfeff',
          noteTextColor: '#0f172a',
          noteBorderColor: '#67e8f9',
          lineColor: '#64748b',
          textColor: '#0f172a'
        }}
      }});
      mermaid.run({{ querySelector: '.mermaid' }});
    }});
  </script>
</body>
</html>
"""


def render_schema_cards(tables: list[dict]):
    """Render parsed tables as styled Streamlit columns."""
    if not tables:
        return False

    chunk_size = 3
    for i in range(0, len(tables), chunk_size):
        row_tables = tables[i : i + chunk_size]
        cols = st.columns(len(row_tables))
        for col, table in zip(cols, row_tables):
            with col:
                st.markdown(
                    f"""
                    <div style="
                        background:#1e1e2e;
                        border:1px solid #7c3aed;
                        border-radius:8px;
                        padding:12px;
                        margin-bottom:12px;
                    ">
                    <h4 style="color:#a78bfa;margin:0 0 8px 0;">📋 {table['name']}</h4>
                    """,
                    unsafe_allow_html=True,
                )
                for col_def in table["columns"]:
                    cname = col_def["name"]
                    ctype = col_def["type"]
                    cstr  = col_def["constraints"].upper()

                    if "PRIMARY KEY" in cstr:
                        icon, color = "🔑", "#fbbf24"
                    elif "REFERENCES" in cstr or "FOREIGN" in cstr:
                        icon, color = "🔗", "#60a5fa"
                    elif "NOT NULL" in cstr:
                        icon, color = "●", "#34d399"
                    else:
                        icon, color = "○", "#9ca3af"

                    st.markdown(
                        f"<p style='margin:2px 0;font-size:13px;'>"
                        f"<span style='color:{color}'>{icon}</span> "
                        f"<span style='color:#e2e8f0'>{cname}</span> "
                        f"<span style='color:#64748b'>{ctype}</span>"
                        f"</p>",
                        unsafe_allow_html=True,
                    )
                st.markdown("</div>", unsafe_allow_html=True)
    return True


# ── Custom CSS ──────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');

    html, body, [class*="css"] {
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    }

    .stApp {
        background: linear-gradient(180deg, #0a0a1a 0%, #0f0f2d 30%, #1a1a3e 100%);
    }

    .block-container {
        max-width: 1400px;
        padding-top: 1rem;
    }

    /* ── Header ── */
    .ghost-header {
        text-align: center;
        padding: 2.5rem 1rem 1.5rem;
        margin-bottom: 1.5rem;
        background: linear-gradient(135deg, rgba(120, 60, 240, 0.12) 0%, rgba(60, 120, 240, 0.08) 50%, rgba(120, 60, 240, 0.04) 100%);
        border-radius: 24px;
        border: 1px solid rgba(120, 60, 240, 0.15);
        position: relative;
        overflow: hidden;
    }
    .ghost-header::before {
        content: '';
        position: absolute;
        top: -50%;
        left: -50%;
        width: 200%;
        height: 200%;
        background: radial-gradient(circle at 30% 50%, rgba(120, 60, 240, 0.06) 0%, transparent 50%),
                    radial-gradient(circle at 70% 50%, rgba(60, 120, 240, 0.06) 0%, transparent 50%);
        pointer-events: none;
    }
    .ghost-header h1 {
        font-size: 3rem;
        font-weight: 800;
        background: linear-gradient(135deg, #c084fc 0%, #818cf8 50%, #60a5fa 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
        margin: 0 0 0.5rem;
        letter-spacing: -0.03em;
        position: relative;
    }
    .ghost-header .subtitle {
        color: rgba(255,255,255,0.55);
        font-size: 1.05rem;
        font-weight: 400;
        margin: 0;
        position: relative;
    }
    .ghost-header .badge-row {
        display: flex;
        justify-content: center;
        gap: 0.75rem;
        margin-top: 1rem;
        position: relative;
        flex-wrap: wrap;
    }
    .ghost-header .badge {
        display: inline-flex;
        align-items: center;
        gap: 0.4rem;
        padding: 0.35rem 0.9rem;
        background: rgba(255,255,255,0.06);
        border: 1px solid rgba(255,255,255,0.08);
        border-radius: 999px;
        color: rgba(255,255,255,0.6);
        font-size: 0.8rem;
        font-weight: 500;
    }
    .ghost-header .badge .dot {
        width: 6px;
        height: 6px;
        border-radius: 50%;
        background: #34d399;
        display: inline-block;
        animation: pulse 2s infinite;
    }
    @keyframes pulse {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.4; }
    }

    /* ── Section titles ── */
    .section-title {
        font-size: 1.1rem;
        font-weight: 700;
        color: rgba(255,255,255,0.9);
        margin-bottom: 1rem;
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }
    .section-title .num {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 24px;
        height: 24px;
        border-radius: 8px;
        background: linear-gradient(135deg, #7c3aed, #6366f1);
        color: white;
        font-size: 0.75rem;
        font-weight: 700;
    }

    /* ── Upload area ── */
    [data-testid="stFileUploader"] {
        border: 2px dashed rgba(120, 60, 240, 0.25);
        border-radius: 16px;
        padding: 0.5rem;
        background: rgba(255,255,255,0.02);
        transition: all 0.2s;
    }
    [data-testid="stFileUploader"]:hover {
        border-color: rgba(120, 60, 240, 0.5);
        background: rgba(255,255,255,0.04);
    }
    [data-testid="stFileUploader"] [data-testid="stMarkdownContainer"] p {
        font-size: 0.9rem;
        color: rgba(255,255,255,0.5);
    }

    /* ── Image preview cards ── */
    .img-card {
        background: rgba(255,255,255,0.04);
        border: 1px solid rgba(255,255,255,0.06);
        border-radius: 12px;
        overflow: hidden;
        transition: all 0.2s;
    }
    .img-card:hover {
        border-color: rgba(120, 60, 240, 0.3);
        transform: translateY(-1px);
    }
    .img-card img {
        width: 100%;
        height: 160px;
        object-fit: cover;
        display: block;
    }
    .img-card .label {
        padding: 0.5rem 0.75rem;
        font-size: 0.75rem;
        color: rgba(255,255,255,0.5);
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        background: rgba(0,0,0,0.2);
    }

    /* ── Generate button ── */
    div.stButton > button {
        background: linear-gradient(135deg, #7c3aed 0%, #6366f1 100%) !important;
        color: white !important;
        border: none !important;
        border-radius: 12px !important;
        padding: 0.7rem 1.5rem !important;
        font-weight: 600 !important;
        font-size: 1rem !important;
        transition: all 0.2s !important;
        box-shadow: 0 4px 20px rgba(120, 60, 240, 0.3) !important;
    }
    div.stButton > button:hover {
        transform: translateY(-2px) !important;
        box-shadow: 0 8px 30px rgba(120, 60, 240, 0.4) !important;
    }
    div.stButton > button:active {
        transform: translateY(0) !important;
    }

    /* ── Result containers ── */
    .result-container {
        background: rgba(255,255,255,0.03);
        border: 1px solid rgba(255,255,255,0.06);
        border-radius: 16px;
        padding: 1.5rem;
        margin-top: 1rem;
    }
    .result-container h3 {
        color: rgba(255,255,255,0.85);
        font-size: 1rem;
        font-weight: 600;
        margin: 0 0 1rem;
    }

    /* ── Code blocks ── */
    [data-testid="stCode"] {
        border-radius: 12px !important;
        border: 1px solid rgba(255,255,255,0.06) !important;
    }
    [data-testid="stCode"] pre {
        background: #0d0d1f !important;
    }

    /* ── Download button row ── */
    .dl-row {
        display: flex;
        gap: 0.75rem;
        margin-top: 1rem;
        flex-wrap: wrap;
    }
    div[data-testid="column"] div.stButton > button {
        background: rgba(255,255,255,0.06) !important;
        box-shadow: none !important;
        font-size: 0.85rem !important;
        padding: 0.5rem 1rem !important;
        border: 1px solid rgba(255,255,255,0.08) !important;
    }
    div[data-testid="column"] div.stButton > button:hover {
        background: rgba(120, 60, 240, 0.15) !important;
        border-color: rgba(120, 60, 240, 0.3) !important;
    }

    /* ── Footer ── */
    .ghost-footer {
        text-align: center;
        padding: 2.5rem 1rem 1rem;
        margin-top: 3rem;
        border-top: 1px solid rgba(255,255,255,0.05);
        color: rgba(255,255,255,0.25);
        font-size: 0.8rem;
    }
    .ghost-footer a {
        color: rgba(120, 60, 240, 0.5);
        text-decoration: none;
        transition: color 0.2s;
    }
    .ghost-footer a:hover {
        color: rgba(120, 60, 240, 0.8);
    }
    .ghost-footer .links {
        display: flex;
        justify-content: center;
        gap: 1.5rem;
        margin-bottom: 0.75rem;
        flex-wrap: wrap;
    }

    /* ── Status info/warning/error overrides ── */
    .stAlert {
        border-radius: 12px !important;
        border: none !important;
    }
    div[data-testid="stNotification"] {
        border-radius: 12px !important;
    }

    /* ── Sidebar ── */
    [data-testid="stSidebar"] {
        background: rgba(15, 15, 40, 0.8);
        border-right: 1px solid rgba(255,255,255,0.04);
    }
    [data-testid="stSidebar"] [data-testid="stMarkdownContainer"] h2,
    [data-testid="stSidebar"] [data-testid="stMarkdownContainer"] h3 {
        color: rgba(255,255,255,0.85);
    }
    [data-testid="stSidebar"] [data-testid="stMarkdownContainer"] p {
        color: rgba(255,255,255,0.5);
        font-size: 0.85rem;
    }
    [data-testid="stSidebar"] hr {
        border-color: rgba(255,255,255,0.06);
    }
    [data-testid="stSidebar"] .stSelectbox label {
        color: rgba(255,255,255,0.6);
        font-size: 0.8rem;
        font-weight: 500;
    }
    [data-testid="stSidebar"] [data-testid="stMarkdownContainer"] .st-info {
        background: rgba(120, 60, 240, 0.1);
        border: 1px solid rgba(120, 60, 240, 0.15);
        color: rgba(255,255,255,0.7);
        font-size: 0.8rem;
    }

    /* ── Tabs ── */
    [data-testid="stTabs"] button {
        border-radius: 10px 10px 0 0 !important;
        font-weight: 500 !important;
        font-size: 0.85rem !important;
    }
    [data-testid="stTabs"] button[aria-selected="true"] {
        background: rgba(120, 60, 240, 0.12) !important;
        border-bottom: 2px solid #7c3aed !important;
    }
</style>
""", unsafe_allow_html=True)


# ── Header ─────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="ghost-header">
    <h1>👻 Ghost Architect</h1>
    <p class="subtitle">Upload UI screenshots → Production-ready PostgreSQL schema + ER Diagram</p>
    <div class="badge-row">
        <span class="badge"><span class="dot"></span> Gemini 2.5 Flash</span>
        <span class="badge">🔒 No GPU needed</span>
        <span class="badge">⚡ Free tier</span>
        <span class="badge">📦 Multi-image</span>
    </div>
</div>
""", unsafe_allow_html=True)

st.markdown(
    "<p style='text-align:center;color:rgba(255,255,255,0.3);font-size:0.85rem;margin-top:-0.5rem;margin-bottom:1.5rem;'>"
    "Drop 3-6 UI screenshots from the same product. Ghost Architect analyzes all evidence and generates a complete database schema.</p>",
    unsafe_allow_html=True,
)

# ── Main layout ────────────────────────────────────────────────────────────────
col_upload, col_schema = st.columns([1, 1], gap="large")

with col_upload:
    st.markdown('<div class="section-title"><span class="num">1</span> Upload Screenshots</div>', unsafe_allow_html=True)

    uploaded_files = st.file_uploader(
        "Upload 3-6 PNG/JPG screenshots from the same product",
        type=["png", "jpg", "jpeg"],
        accept_multiple_files=True,
        label_visibility="collapsed",
    )

    if uploaded_files:
        count = len(uploaded_files)
        is_valid = count >= MIN_REQUIRED_IMAGES

        if is_valid:
            st.markdown(
                f"<p style='color:#34d399;font-size:0.85rem;font-weight:500;margin:0.5rem 0;'>"
                f"✓ {count} screenshot{'s' if count != 1 else ''} uploaded</p>",
                unsafe_allow_html=True,
            )
        else:
            st.markdown(
                f"<p style='color:#fbbf24;font-size:0.85rem;font-weight:500;margin:0.5rem 0;'>"
                f"⚠️ Need at least {MIN_REQUIRED_IMAGES} screenshots ({count} uploaded)</p>",
                unsafe_allow_html=True,
            )

        if count > MAX_RECOMMENDED_IMAGES:
            st.info(f"ℹ️ {MAX_RECOMMENDED_IMAGES} screenshots is the sweet spot. You can continue with {count}.")

        rows = (count + 2) // 3
        for row in range(rows):
            row_files = uploaded_files[row * 3 : (row + 1) * 3]
            cols = st.columns(len(row_files))
            for ci, (col, f) in enumerate(zip(cols, row_files)):
                with col:
                    img_bytes = f.getvalue()
                    img = PIL.Image.open(io.BytesIO(img_bytes)).convert("RGB")
                    st.image(img, use_container_width=True)
                    st.markdown(
                        f"<p style='font-size:0.7rem;color:rgba(255,255,255,0.35);"
                        f"text-align:center;margin-top:-0.3rem;'>{f.name[:20]}{'...' if len(f.name) > 20 else ''}</p>",
                        unsafe_allow_html=True,
                    )
    else:
        st.markdown(
            "<div style='text-align:center;padding:2rem 1rem;border:2px dashed rgba(255,255,255,0.06);"
            "border-radius:16px;'>"
            "<p style='font-size:2.5rem;margin:0;opacity:0.3;'>🖼️</p>"
            "<p style='color:rgba(255,255,255,0.25);font-size:0.9rem;'>Drop screenshots here</p>"
            "</div>",
            unsafe_allow_html=True,
        )

with col_schema:
    st.markdown('<div class="section-title"><span class="num">2</span> Generated Schema</div>', unsafe_allow_html=True)

    if not uploaded_files:
        st.markdown(
            "<div style='text-align:center;padding:2.5rem 1rem;'>"
            "<p style='font-size:3rem;margin:0;opacity:0.2;'>📊</p>"
            "<p style='color:rgba(255,255,255,0.25);font-size:0.9rem;margin-top:0.5rem;'>"
            "Upload screenshots on the left to generate a schema</p>"
            "</div>",
            unsafe_allow_html=True,
        )
    elif len(uploaded_files) < MIN_REQUIRED_IMAGES:
        st.markdown(
            "<div style='text-align:center;padding:2.5rem 1rem;'>"
            "<p style='font-size:3rem;margin:0;opacity:0.2;'>📸</p>"
            "<p style='color:rgba(255,255,255,0.25);font-size:0.9rem;margin-top:0.5rem;'>"
            f"Upload {MIN_REQUIRED_IMAGES - len(uploaded_files)} more screenshot{'s' if MIN_REQUIRED_IMAGES - len(uploaded_files) != 1 else ''} for precise schema generation</p>"
            "</div>",
            unsafe_allow_html=True,
        )
    else:
        with st.container():
            generate_btn = st.button(
                "🚀 Generate Schema Architecture",
                type="primary",
                use_container_width=True,
            )

        if generate_btn:
            # Rate limit guard
            if "request_count" not in st.session_state:
                st.session_state.request_count = 0

            if st.session_state.request_count >= 3:
                st.warning(
                    "You've used 3 free analyses this session. "
                    "Refresh to continue, or check the repo to run locally."
                )
                st.stop()

            pil_images = []
            for uploaded_file in uploaded_files:
                img = PIL.Image.open(io.BytesIO(uploaded_file.getvalue()))
                if img.mode != "RGB":
                    img = img.convert("RGB")
                pil_images.append(img)

            # Analysis with progress
            status_ph = st.empty()
            status_ph.markdown(
                "<div style='text-align:center;padding:2rem;'>"
                "<p style='font-size:1.5rem;margin:0;'>🔮</p>"
                "<p style='color:rgba(255,255,255,0.6);margin-top:0.75rem;'>"
                "Analyzing UI evidence across all screenshots...</p>"
                "<div style='width:100%;height:4px;background:rgba(255,255,255,0.06);"
                "border-radius:4px;margin-top:1rem;overflow:hidden;'>"
                "<div style='width:40%;height:100%;background:linear-gradient(90deg,#7c3aed,#6366f1);"
                "border-radius:4px;animation:shimmer 1.5s infinite;'></div>"
                "</div>"
                "<style>@keyframes shimmer { 0% { transform:translateX(-100%); } 100% { transform:translateX(350%); } }</style>"
                "</div>",
                unsafe_allow_html=True,
            )

            try:
                raw_output, model_used = analyze_screenshots(pil_images, dialect)
                st.session_state.request_count += 1
            except Exception as e:
                err_str = str(e)
                if "API_KEY_INVALID" in err_str or "PERMISSION_DENIED" in err_str or "UNAUTHENTICATED" in err_str:
                    st.error(
                        "⚠️ **Gemini API key is invalid or expired.**\n\n"
                        "The app admin needs to update the API key in `.streamlit/secrets.toml` "
                        "(local) or Streamlit Cloud Secrets (deployed).\n\n"
                        "Get a new key at https://aistudio.google.com → Get API Key."
                    )
                elif "429" in err_str or "RESOURCE_EXHAUSTED" in err_str:
                    st.error(
                        "⚠️ **API rate limit reached.**\n\n"
                        "Too many requests. Wait a minute and try again."
                    )
                elif "503" in err_str or "UNAVAILABLE" in err_str:
                    st.error(
                        "⚠️ **Gemini service is temporarily unavailable.**\n\n"
                        "This is usually transient. Please try again in a few seconds."
                    )
                else:
                    st.error(f"Analysis failed: {err_str}")
                status_ph.empty()
                st.stop()

            status_ph.empty()

            # Parse & show results
            parsed = split_consolidated_output(raw_output)

            st.markdown(
                f"<p style='color:rgba(255,255,255,0.35);font-size:0.75rem;margin:0 0 0.75rem;'>"
                f"Generated by {model_used}  ·  {len(uploaded_files)} screenshots analyzed</p>",
                unsafe_allow_html=True,
            )

            # Explanation
            if parsed["explanation"]:
                st.markdown(
                    f"<div style='background:rgba(120,60,240,0.08);border:1px solid rgba(120,60,240,0.12);"
                    f"border-radius:12px;padding:1rem;margin-bottom:1rem;'>"
                    f"<p style='color:rgba(255,255,255,0.6);font-size:0.85rem;margin:0;'>"
                    f"<strong style='color:rgba(255,255,255,0.8);'>Design decisions:</strong> "
                    f"{parsed['explanation']}</p></div>",
                    unsafe_allow_html=True,
                )

            # Results in tabs
            tab_vis, tab_sql = st.tabs(["📊 ER Diagram", "💻 SQL Schema"])

            with tab_vis:
                if parsed["mermaid"]:
                    mermaid_html = build_mermaid_html(
                        parsed["mermaid"],
                        "Ghost Architect: Database Schema",
                        parsed["sql"] or "",
                    )
                    st.components.v1.html(mermaid_html, height=900, scrolling=True)
                else:
                    if parsed["sql"]:
                        parsed_tables = parse_create_tables(parsed["sql"])
                        if parsed_tables:
                            render_schema_cards(parsed_tables)
                    st.info("Mermaid diagram not available. Showing SQL below.")

            with tab_sql:
                if parsed["sql"]:
                    st.code(parsed["sql"], language="sql")
                else:
                    st.code(raw_output, language="text")

            # Download buttons
            if parsed["sql"] or parsed["mermaid"]:
                st.markdown("<div style='margin-top:1rem;'>", unsafe_allow_html=True)
                dl_col1, dl_col2, dl_col3, _ = st.columns([1, 1, 1.5, 0.5])

                if parsed["sql"]:
                    dl_col1.download_button(
                        label="📄 Download SQL",
                        data=parsed["sql"],
                        file_name="ghost_architect_schema.sql",
                        mime="text/plain",
                        use_container_width=True,
                    )

                if parsed["mermaid"]:
                    dl_col2.download_button(
                        label="📊 Download Mermaid",
                        data=parsed["mermaid"],
                        file_name="ghost_architect_schema.mmd",
                        mime="text/plain",
                        use_container_width=True,
                    )

                if parsed["sql"] and parsed["mermaid"]:
                    report = f"""# Ghost Architect — Database Schema

## Design Decisions
{parsed.get('explanation', 'N/A')}

## Entity Relationship Diagram
```mermaid
{parsed['mermaid']}
```

## PostgreSQL DDL
```sql
{parsed['sql']}
```
"""
                    dl_col3.download_button(
                        label="📦 Download Full Report (.md)",
                        data=report,
                        file_name="ghost_architect_schema_report.md",
                        mime="text/markdown",
                        use_container_width=True,
                    )
                st.markdown("</div>", unsafe_allow_html=True)

            # Fallback schema cards
            if not parsed["mermaid"] and not parsed["sql"]:
                parsed_tables = parse_create_tables(raw_output)
                if parsed_tables:
                    render_schema_cards(parsed_tables)


# ── Footer ─────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="ghost-footer">
    <div class="links">
        <a href="https://github.com/HarshilMaks/ghost_architect_gemma3" target="_blank">GitHub</a>
        <a href="https://huggingface.co/harshilmaks/ghost-architect-gemma3-adapter" target="_blank">HuggingFace Model</a>
        <a href="https://aistudio.google.com" target="_blank">Gemini API</a>
    </div>
    <p>Ghost Architect · Fine-tuned Gemma-3-12B + Gemini API · Apache 2.0</p>
</div>
""", unsafe_allow_html=True)
