import re
import io
import html as html_lib
from uuid import uuid4
from pathlib import Path

import streamlit as st
from google import genai
from google.genai import types
import PIL.Image
import facade

# ── Page config (must be first Streamlit call) ───────────────────────────────
st.set_page_config(
    page_title="Ghost Architect",
    page_icon="👻",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Facade theme ───────────────────────────────────────────────────────────────
facade.theme.apply(
    preset="dark",
    primary="#3B82F6",
    primary_foreground="#FFFFFF",
    background="#0a0a0f",
    foreground="#E2E8F0",
    muted="#111118",
    muted_foreground="#8A8A9E",
    border="#252533",
    chrome_background="#0d0d14",
    chrome_foreground="#E2E8F0",
    chrome_border="#1a1a24",
    font_sans="Inter, system-ui",
    radius="md",
)

MIN_REQUIRED_IMAGES = 3
MAX_RECOMMENDED_IMAGES = 6
SCHEMA_PROMPT = """You are a senior database architect at Microsoft. Analyze ALL uploaded UI screenshots together — they belong to the same production web application.

Your task: produce a complete, enterprise-grade database schema that a developer can implement immediately.

## Screenshot Analysis Protocol
1. **List/Table view**: Identify the main entity, every column header (these are your fields), sort/filter controls (these hint at indexes), and action buttons (create, edit, delete — these define CRUD).
2. **Create/Edit form**: Every labeled input, dropdown, checkbox, date picker, textarea, and file upload maps to a column. Required-field indicators (*) → NOT NULL. Input types guide data types.
3. **Detail/Dashboard view**: Additional fields not in forms/lists. Aggregated counts hint at summary queries or materialized views.

## Schema Requirements
- Every table: `id UUID PRIMARY KEY DEFAULT gen_random_uuid()`, `created_at TIMESTAMPTZ DEFAULT NOW()`, `updated_at TIMESTAMPTZ DEFAULT NOW()`
- Infer data types from UI elements: text input → VARCHAR(255) or TEXT, number/spinbox → INTEGER or DECIMAL, date picker → DATE, datetime picker → TIMESTAMPTZ, checkbox → BOOLEAN, select/radio → VARCHAR or ENUM, file upload → TEXT (URL) or BYTEA
- Foreign keys: every relationship visible in the UI gets an FK column with REFERENCES and ON DELETE CASCADE (child data) or RESTRICT (critical records)
- Indexes: CREATE INDEX on every FK column, every column used in sort/filter, every column used in search
- Constraints: NOT NULL on all required fields, UNIQUE on natural identifiers (email, username, slug), CHECK on columns with validatable ranges
- Naming: snake_case, singular table names (`user`, `organization`, not `users`, `organizations`), FK columns named `{referenced_table}_id`
- Junction tables for many-to-many: named `{table_a}_{table_b}`, composite PK on both FKs
- Enums: CREATE TYPE for columns with 3-7 fixed values visible in the UI
- Table comments: COMMENT ON TABLE for every table explaining what real-world entity it models
- Column comments: COMMENT ON COLUMN for any non-obvious column (status codes, relationship meanings)

## Output Format — EXACTLY this structure, nothing before ===, nothing after last line:

=== MERMAID ===
erDiagram
    [Complete Mermaid ER diagram. Every table, every column, every relationship with proper cardinality notation (||--o{, ||--||, }o--o{). Include PK markers, FK markers, and column types in the entity blocks.]

=== SQL ===
-- PostgreSQL Schema generated by Ghost Architect
[All CREATE TYPE, CREATE TABLE, CREATE INDEX, and COMMENT ON statements in dependency order. No ALTER TABLE — use inline FK references.]

=== EXPLANATION ===
[3-4 sentences: key entities identified, how UI patterns mapped to relationships, notable design decisions, and any assumptions made about invisible state/authentication.]"""


# ── Gemini API ────────────────────────────────────────────────────────────────
def _get_client():
    key = st.session_state.get("user_api_key", "").strip() or st.secrets.get("GEMINI_API_KEY", "")
    return genai.Client(api_key=key)


MODEL_CANDIDATES = [
    "gemini-3.5-flash",
    "gemini-3.1-flash-lite",
    "gemini-3-flash-preview",
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
    "gemini-2.5-flash-image",
    "gemini-2.0-flash",
    "gemini-flash-latest",
]


def analyze_screenshots(pil_images: list, dialect: str = "PostgreSQL") -> tuple[str, str]:
    """Send images to Gemini with model fallback chain. Returns (raw_output, model_used)."""
    client = _get_client()
    dialect_note = f"\n\nGenerate schema for {dialect}. Use correct {dialect} syntax and native data types."
    prompt = SCHEMA_PROMPT + dialect_note
    contents = [prompt] + pil_images
    config = types.GenerateContentConfig(temperature=0.1, max_output_tokens=4096)

    last_error = None
    for model_name in MODEL_CANDIDATES:
        try:
            response = client.models.generate_content(
                model=model_name, contents=contents, config=config
            )
            text = response.text.strip()
            if not text:
                last_error = ValueError(f"{model_name} returned empty response")
                continue
            if "=== SQL ===" in text and "=== MERMAID ===" in text:
                return text, model_name
            last_error = ValueError(f"{model_name} didn't follow output format")
        except Exception as e:
            last_error = e
    raise last_error or RuntimeError("All models failed to generate valid output")


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("**Ghost Architect**")
    st.caption("UI → Database Schema")
    st.divider()

    dialect = st.selectbox(
        "Target database dialect",
        ["PostgreSQL", "MySQL 8.0+", "SQLite"],
        index=0,
        help="Changes the SQL syntax and data types in the generated schema."
    )

    st.markdown("**How it works**")
    st.markdown(
        "1. Upload 3–6 UI screenshots from the same web app\n"
        "2. Include list view, form, and detail screens\n"
        "3. Click Generate Schema → get SQL + ER diagram"
    )
    st.caption("3 analyses per session · No GPU required")

    st.divider()
    with st.expander("🔑 Use your own API key"):
        st.caption("If the admin key is expired or unavailable, paste your own Gemini API key here.")
        user_key = st.text_input(
            "Gemini API Key",
            type="password",
            placeholder="Paste your API key",
            label_visibility="collapsed",
            key="user_api_key_input",
        )
        if user_key:
            st.session_state.user_api_key = user_key
            st.success("Custom API key set for this session.")
        elif "user_api_key" in st.session_state:
            del st.session_state.user_api_key


# ── SQL Parser (shared with inference.py) ────────────────────────────────────
def _split_sql_columns(body: str) -> list[str]:
    """Split CREATE TABLE body by top-level commas (keeps DECIMAL(10,2) intact)."""
    parts = []
    current = []
    depth = 0
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth = max(0, depth - 1)
        if ch == "," and depth == 0:
            part = "".join(current).strip()
            if part:
                parts.append(part)
            current = []
            continue
        current.append(ch)
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def parse_create_tables(sql: str) -> list[dict]:
    """Extract CREATE TABLE blocks → list of {name, columns}."""
    tables = []
    pattern = re.compile(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`\"]?(\w+)[`\"]?\s*\((.*?)\)\s*;",
        re.IGNORECASE | re.DOTALL,
    )
    for match in pattern.finditer(sql):
        table_name = match.group(1)
        body = match.group(2)
        columns = []
        for raw_line in _split_sql_columns(body):
            line = raw_line.strip().rstrip(",")
            if not line:
                continue
            if re.match(r"(PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT)\s", line, re.IGNORECASE):
                continue
            parts = line.split()
            if not parts:
                continue
            col_name    = parts[0].strip('`"')
            col_type    = parts[1] if len(parts) > 1 else "?"
            constraints = " ".join(parts[2:]) if len(parts) > 2 else ""
            columns.append({"name": col_name, "type": col_type, "constraints": constraints})
        if columns:
            tables.append({"name": table_name, "columns": columns})
    return tables


def _merge_constraints(existing: str, new: str) -> str:
    existing = existing.strip()
    new = new.strip()
    if not existing:
        return new
    if not new:
        return existing
    merged_tokens = []
    for token in f"{existing} {new}".split():
        if token not in merged_tokens:
            merged_tokens.append(token)
    return " ".join(merged_tokens)


def merge_table_sets(table_sets: list[list[dict]]) -> list[dict]:
    """Merge tables from multiple screenshots into a single consolidated schema.

    NOTE: This is a lightweight fallback parser for rendering visual cards.
    The real "conflict resolution" happens in the Gemini consolidation prompt.
    """
    merged: dict[str, dict] = {}
    for tables in table_sets:
        for table in tables:
            table_key = table["name"].lower()
            if table_key not in merged:
                merged[table_key] = {
                    "name": table["name"],
                    "columns_by_key": {},
                    "column_order": [],
                }
            table_entry = merged[table_key]
            for col in table["columns"]:
                col_key = col["name"].lower()
                existing = table_entry["columns_by_key"].get(col_key)
                if existing is None:
                    table_entry["columns_by_key"][col_key] = {
                        "name": col["name"],
                        "type": col["type"],
                        "constraints": col["constraints"],
                    }
                    table_entry["column_order"].append(col_key)
                    continue

                if existing["type"] in {"?", "TEXT"} and col["type"] not in {"?", "TEXT"}:
                    existing["type"] = col["type"]
                if len(col["constraints"].strip()) > len(existing["constraints"].strip()):
                    existing["constraints"] = col["constraints"]
                else:
                    existing["constraints"] = _merge_constraints(
                        existing["constraints"], col["constraints"]
                    )

    result = []
    for table_key in sorted(merged):
        table_entry = merged[table_key]
        columns = [
            table_entry["columns_by_key"][col_key]
            for col_key in table_entry["column_order"]
        ]
        result.append({"name": table_entry["name"], "columns": columns})
    return result


def _normalize_identifier(name: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9_]+", "_", name.strip().lower())
    return normalized.strip("_") or "unnamed_entity"


def tables_to_sql(tables: list[dict]) -> str:
    """Render merged table representation back into SQL CREATE TABLE statements.

    NOTE: This is a fallback for visual rendering only. The *authoritative* consolidated
    SQL comes from Gemini, not this function.
    """
    statements = []
    for table in tables:
        table_name = _normalize_identifier(table["name"])
        column_lines = []
        for col in table["columns"]:
            col_name = _normalize_identifier(col["name"])
            col_type = col["type"] if col["type"] and col["type"] != "?" else "TEXT"
            constraints = col["constraints"].strip()
            suffix = f" {constraints}" if constraints else ""
            column_lines.append(f"    {col_name} {col_type}{suffix}")
        statements.append(
            f"CREATE TABLE {table_name} (\n" + ",\n".join(column_lines) + "\n);"
        )
    return "\n\n".join(statements)


def _strip_markdown_code_fence(text: str) -> str:
    """Remove optional markdown triple-backtick wrappers."""
    stripped = text.strip()
    fenced = re.match(r"^```[a-zA-Z0-9_+-]*\s*\n(.*?)\n```$", stripped, re.DOTALL)
    if fenced:
        return fenced.group(1).strip()
    return stripped


def split_consolidated_output(raw_output: str) -> dict:
    """
    Parse raw Gemini output into mermaid, sql, and explanation sections.
    Returns dict with keys: mermaid, sql, explanation (each str or None).
    """
    result = {"mermaid": None, "sql": None, "explanation": None}

    has_mermaid = "=== MERMAID ===" in raw_output
    has_sql = "=== SQL ===" in raw_output
    has_explanation = "=== EXPLANATION ===" in raw_output

    if has_mermaid and has_sql:
        mermaid_start = raw_output.find("=== MERMAID ===") + len("=== MERMAID ===")
        mermaid_end = raw_output.find("=== SQL ===")
        result["mermaid"] = _strip_markdown_code_fence(raw_output[mermaid_start:mermaid_end].strip())

    if has_sql:
        sql_start = raw_output.find("=== SQL ===") + len("=== SQL ===")
        sql_end = raw_output.find("=== EXPLANATION ===") if has_explanation else len(raw_output)
        result["sql"] = _strip_markdown_code_fence(raw_output[sql_start:sql_end].strip())

    if has_explanation:
        exp_start = raw_output.find("=== EXPLANATION ===") + len("=== EXPLANATION ===")
        result["explanation"] = raw_output[exp_start:].strip()

    return result


def build_mermaid_html(mermaid_diagram: str, title: str, sql_source: str = "") -> str:
    """Build a polished Mermaid preview HTML with diagram, source blocks, and SQL."""
    safe_title = html_lib.escape(title)
    safe_sql = html_lib.escape(sql_source.strip())
    mermaid_source = _strip_markdown_code_fence(mermaid_diagram).strip()
    safe_mermaid_source = html_lib.escape(mermaid_source)
    diagram_source = safe_mermaid_source or "erDiagram\\n    %% No Mermaid diagram found."

    mermaid_block = f"""
        <details>
          <summary>Show Mermaid source</summary>
          <pre class="source-block">{safe_mermaid_source or "(empty)"}</pre>
        </details>
        """
    sql_block = f"""
        <details>
          <summary>Show SQL statements</summary>
          <pre class="source-block">{safe_sql or "(empty)"}</pre>
        </details>
        """ if safe_sql else ""

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{safe_title}</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f8fafc;
      --panel: #ffffff;
      --border: #dbe4ee;
      --text: #0f172a;
      --muted: #475569;
      --accent: #2563eb;
      --accent-soft: #dbeafe;
    }}
    body {{
      margin: 0;
      background: linear-gradient(180deg, #f8fafc 0%, #eef2ff 100%);
      color: var(--text);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    .page {{
      max-width: 1600px;
      margin: 0 auto;
      padding: 24px;
    }}
    .header {{
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
      margin-bottom: 18px;
    }}
    .title {{
      margin: 0;
      font-size: 24px;
      letter-spacing: -0.02em;
    }}
    .subtitle {{
      margin: 4px 0 0;
      color: var(--muted);
      font-size: 14px;
    }}
    .badge {{
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 8px 12px;
      border: 1px solid var(--border);
      border-radius: 999px;
      background: rgba(255,255,255,0.85);
      font-size: 13px;
      color: var(--muted);
      box-shadow: 0 8px 24px rgba(15, 23, 42, 0.04);
    }}
    .card {{
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 20px;
      box-shadow: 0 18px 50px rgba(15, 23, 42, 0.08);
      overflow: hidden;
    }}
    .card-head {{
      padding: 18px 20px 0;
    }}
    .eyebrow {{
      display: inline-flex;
      align-items: center;
      padding: 6px 10px;
      border-radius: 999px;
      background: var(--accent-soft);
      color: #1d4ed8;
      font-size: 12px;
      font-weight: 800;
      letter-spacing: 0.03em;
      text-transform: uppercase;
    }}
    .description {{
      margin: 10px 0 0;
      color: var(--muted);
      font-size: 14px;
      line-height: 1.5;
    }}
    .diagram-wrap {{
      margin: 18px 20px 0;
      padding: 20px;
      border: 1px solid #cbd5e1;
      border-radius: 18px;
      background: linear-gradient(180deg, #eef2ff 0%, #f8fafc 52%, #e2e8f0 100%);
      overflow: auto;
      min-height: 400px;
    }}
    .diagram-wrap .mermaid {{
      min-width: fit-content;
      width: 100%;
      padding: 16px;
      border-radius: 16px;
      background: linear-gradient(180deg, rgba(255,255,255,0.7) 0%, rgba(248,250,252,0.92) 100%);
    }}
    .diagram-wrap svg {{
      max-width: none !important;
      width: auto !important;
      min-width: 100% !important;
      height: auto !important;
      background: linear-gradient(180deg, #f8fafc 0%, #eef2ff 100%) !important;
      border-radius: 16px;
      box-shadow: inset 0 0 0 1px rgba(148, 163, 184, 0.18);
    }}
    .source-block {{
      margin: 0;
      padding: 16px;
      overflow-x: auto;
      white-space: pre;
      background: #0f172a;
      color: #e2e8f0;
      border: 1px solid #1e293b;
      border-radius: 14px;
      font-size: 13px;
      line-height: 1.55;
    }}
    details {{
      border-top: 1px solid var(--border);
      padding: 16px 20px 18px;
      background: #f8fafc;
    }}
    details summary {{
      cursor: pointer;
      color: var(--accent);
      font-weight: 700;
      margin-bottom: 12px;
    }}
    details pre {{
      margin: 0;
      padding: 16px;
      overflow-x: auto;
      white-space: pre-wrap;
      word-break: break-word;
      background: #0f172a;
      color: #e2e8f0;
      border: 1px solid #1e293b;
      border-radius: 14px;
      font-size: 13px;
      line-height: 1.5;
    }}
    .footer-note {{
      padding: 0 20px 20px;
      color: var(--muted);
      font-size: 13px;
    }}
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div>
        <h1 class="title">{safe_title}</h1>
        <p class="subtitle">Premium Mermaid ER diagram with database relationships.</p>
      </div>
      <div class="badge">Ghost Architect · Gemini API</div>
    </div>

    <div class="card">
      <div class="card-head">
        <span class="eyebrow">Database Schema</span>
        <p class="description">Visual ER diagram of your inferred PostgreSQL schema</p>
      </div>
      <div class="diagram-wrap">
        <div class="mermaid">
{diagram_source}
        </div>
      </div>
      {mermaid_block}
      {sql_block}
      <div class="footer-note">Copy the SQL statements or use the Mermaid diagram in any renderer.</div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script>
    window.addEventListener('DOMContentLoaded', () => {{
      mermaid.initialize({{
        startOnLoad: false,
        theme: 'base',
        securityLevel: 'loose',
        darkMode: false,
        er: {{
          useMaxWidth: true,
          layoutDirection: 'TB',
          diagramPadding: 40,
          minEntityWidth: 120,
          entityPadding: 20
        }},
        themeVariables: {{
          fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
          fontSize: '16px',
          background: '#eef2ff',
          primaryColor: '#eff6ff',
          primaryTextColor: '#0f172a',
          primaryBorderColor: '#60a5fa',
          secondaryColor: '#f8fafc',
          secondaryTextColor: '#0f172a',
          secondaryBorderColor: '#cbd5e1',
          tertiaryColor: '#ffffff',
          tertiaryTextColor: '#0f172a',
          noteBkgColor: '#ecfeff',
          noteTextColor: '#0f172a',
          noteBorderColor: '#67e8f9',
          lineColor: '#64748b',
          textColor: '#0f172a'
        }}
      }});
      mermaid.run({{ querySelector: '.mermaid' }});
    }});
  </script>
</body>
</html>
"""


def render_schema_cards(tables: list[dict]):
    """Render parsed tables as styled Streamlit columns."""
    if not tables:
        return False

    chunk_size = 3
    for i in range(0, len(tables), chunk_size):
        row_tables = tables[i : i + chunk_size]
        cols = st.columns(len(row_tables))
        for col, table in zip(cols, row_tables):
            with col:
                st.markdown(
                    f"""
                    <div style="
                        background:#1e1e2e;
                        border:1px solid #7c3aed;
                        border-radius:8px;
                        padding:12px;
                        margin-bottom:12px;
                    ">
                    <h4 style="color:#a78bfa;margin:0 0 8px 0;">📋 {table['name']}</h4>
                    """,
                    unsafe_allow_html=True,
                )
                for col_def in table["columns"]:
                    cname = col_def["name"]
                    ctype = col_def["type"]
                    cstr  = col_def["constraints"].upper()

                    if "PRIMARY KEY" in cstr:
                        icon, color = "🔑", "#fbbf24"
                    elif "REFERENCES" in cstr or "FOREIGN" in cstr:
                        icon, color = "🔗", "#60a5fa"
                    elif "NOT NULL" in cstr:
                        icon, color = "●", "#34d399"
                    else:
                        icon, color = "○", "#9ca3af"

                    st.markdown(
                        f"<p style='margin:2px 0;font-size:13px;'>"
                        f"<span style='color:{color}'>{icon}</span> "
                        f"<span style='color:#e2e8f0'>{cname}</span> "
                        f"<span style='color:#64748b'>{ctype}</span>"
                        f"</p>",
                        unsafe_allow_html=True,
                    )
                st.markdown("</div>", unsafe_allow_html=True)
    return True


# ── Custom CSS (app-specific overrides only) ──────────────────────────────────
st.markdown("""
<style>
    .stApp { background: #0a0a0f; }
    .block-container { max-width: 1400px; }
    .upload-empty { text-align: center; padding: 2rem 1rem; border: 2px dashed #252533; border-radius: 12px; color: #4a4a5e; font-size: 0.9rem; }
    [data-testid="stFileUploader"] { border: 2px dashed #252533; border-radius: 12px; padding: 0.5rem; transition: all 0.2s; }
    [data-testid="stFileUploader"]:hover { border-color: #3b82f6; }
    [data-testid="stFileUploader"] [data-testid="stMarkdownContainer"] p { font-size: 0.9rem; color: #6b6b80; }
    [data-testid="stCode"] { border-radius: 12px !important; border: 1px solid #252533 !important; }
    [data-testid="stCode"] pre { background: #0d0d14 !important; }
    .ghost-footer { text-align: center; padding: 2.5rem 1rem 1rem; margin-top: 3rem; border-top: 1px solid #1a1a24; color: #4a4a5e; font-size: 0.8rem; }
    .ghost-footer a { color: #6b6b80; text-decoration: none; transition: color 0.2s; }
    .ghost-footer a:hover { color: #a0a0b5; }
    .ghost-footer .links { display: flex; justify-content: center; gap: 1.5rem; margin-bottom: 0.75rem; flex-wrap: wrap; }
    @keyframes shimmer { 0% { transform:translateX(-100%); } 100% { transform:translateX(350%); } }
    div[data-testid="stButton"] button { width: 100% !important; font-size: 1.1rem !important; padding: 0.6rem 1rem !important; font-weight: 600 !important; }
    section[data-testid="stSidebar"] { width: 280px !important; }
</style>
""", unsafe_allow_html=True)


# ── Header ─────────────────────────────────────────────────────────────────────
st.markdown(
    '<h1 style="text-align:center;font-size:1.8rem;font-weight:700;'
    'margin:1rem 0 0.15rem;color:#E2E8F0;">👻 Ghost Architect</h1>',
    unsafe_allow_html=True,
)
st.markdown(
    '<p style="text-align:center;color:#8A8A9E;margin:0 0 1.25rem;font-size:0.9rem;">'
    'UI screenshots \u2192 PostgreSQL Schema + ER Diagram</p>',
    unsafe_allow_html=True,
)

# ── Main layout ────────────────────────────────────────────────────────────────
col_upload, col_schema = st.columns([1, 1], gap="large")

with col_upload:
    st.markdown('<p style="font-size:1.1rem;font-weight:700;color:#E2E8F0;margin-bottom:1rem;">1. Upload Screenshots</p>', unsafe_allow_html=True)

    uploaded_files = st.file_uploader(
        "Upload screenshots (PNG / JPG)",
        type=["png", "jpg", "jpeg"],
        accept_multiple_files=True,
        label_visibility="collapsed",
    )

    if uploaded_files:
        count = len(uploaded_files)
        if count >= MIN_REQUIRED_IMAGES:
            st.success(f"{count} screenshots uploaded")
        else:
            st.warning(f"Need at least {MIN_REQUIRED_IMAGES} screenshots ({count} uploaded)")

        if count > MAX_RECOMMENDED_IMAGES:
            st.info(f"{MAX_RECOMMENDED_IMAGES} screenshots is the sweet spot. You can continue with {count}.")

        rows = (count + 2) // 3
        for row in range(rows):
            row_files = uploaded_files[row * 3 : (row + 1) * 3]
            cols = st.columns(len(row_files))
            for ci, (col, f) in enumerate(zip(cols, row_files)):
                with col:
                    st.image(PIL.Image.open(io.BytesIO(f.getvalue())).convert("RGB"), use_container_width=True)
                    st.markdown(f'<p style="font-size:0.7rem;color:#8A8A9E;text-align:center;margin-top:-0.3rem;">{f.name[:20]}{"..." if len(f.name) > 20 else ""}</p>', unsafe_allow_html=True)
    else:
        st.markdown('<div class="upload-empty">Drop screenshots here</div>', unsafe_allow_html=True)

with col_schema:
    if not uploaded_files:
        st.markdown('<p style="font-size:1.1rem;font-weight:700;color:#E2E8F0;margin-bottom:1rem;">2. Generated Schema</p>', unsafe_allow_html=True)
        st.info("Upload screenshots on the left", icon="📸")
    elif len(uploaded_files) < MIN_REQUIRED_IMAGES:
        st.markdown('<p style="font-size:1.1rem;font-weight:700;color:#E2E8F0;margin-bottom:1rem;">2. Generated Schema</p>', unsafe_allow_html=True)
        st.info(f"Upload {MIN_REQUIRED_IMAGES - len(uploaded_files)} more screenshot{'s' if MIN_REQUIRED_IMAGES - len(uploaded_files) != 1 else ''}", icon="📸")


# ── Generate button (full width) ──────────────────────────────────────────────
if uploaded_files and len(uploaded_files) >= MIN_REQUIRED_IMAGES:
    generate_btn = st.button("\u2726 Generate Schema", type="primary", use_container_width=True, key="generate_btn")

    if generate_btn:
        if "request_count" not in st.session_state:
            st.session_state.request_count = 0
        if st.session_state.request_count >= 3:
            st.warning("You've used 3 free analyses this session. Refresh to continue.")
            st.stop()

        pil_images = []
        for f in uploaded_files:
            img = PIL.Image.open(io.BytesIO(f.getvalue()))
            if img.mode != "RGB":
                img = img.convert("RGB")
            pil_images.append(img)

        status_ph = st.empty()
        status_ph.markdown(f'<div style="text-align:center;padding:2rem;"><p style="color:#8A8A9E;margin-top:0.75rem;">Analyzing UI evidence across all screenshots...</p><div style="width:100%;height:4px;background:#1a1a24;border-radius:4px;margin-top:1rem;overflow:hidden;"><div style="width:40%;height:100%;background:#2563eb;border-radius:4px;animation:shimmer 1.5s infinite;"></div></div></div>', unsafe_allow_html=True)

        try:
            raw_output, model_used = analyze_screenshots(pil_images, dialect)
            st.session_state.request_count += 1
        except Exception as e:
            err_str = str(e)
            if "denied access" in err_str or "PERMISSION_DENIED" in err_str:
                st.error(f"Google Cloud project denied access. Get a new API key from a different project at https://aistudio.google.com.\n\n{err_str[:200]}")
            elif "API_KEY_INVALID" in err_str or "UNAUTHENTICATED" in err_str:
                st.error("Gemini API key is invalid or expired. Get a new one at https://aistudio.google.com.")
            elif "429" in err_str or "RESOURCE_EXHAUSTED" in err_str:
                st.warning("API rate limit reached. Wait a moment and try again.")
            elif "503" in err_str or "UNAVAILABLE" in err_str:
                st.error("Gemini service is temporarily unavailable. Try again in a few seconds.")
            else:
                st.error(f"Analysis failed: {err_str}")
            status_ph.empty()
            st.stop()

        status_ph.empty()
        parsed = split_consolidated_output(raw_output)
        st.session_state.last_mermaid = parsed["mermaid"]
        st.session_state.last_sql = parsed["sql"]
        st.session_state.last_explanation = parsed["explanation"]
        st.session_state.last_model = model_used
        st.session_state.last_raw_output = raw_output


# ── Results (cached in session state, persists across reruns) ─────────────────
if st.session_state.get("last_sql") or st.session_state.get("last_mermaid"):
    st.markdown(f'<p style="color:#8A8A9E;font-size:0.75rem;margin:0.5rem 0 0.75rem;">Generated by {st.session_state.last_model}</p>', unsafe_allow_html=True)

    if st.session_state.get("last_explanation"):
        with st.container(border=True):
            st.markdown(f'<p style="color:#8A8A9E;font-size:0.85rem;margin:0;"><strong style="color:#E2E8F0;">Design decisions:</strong> {st.session_state.last_explanation}</p>', unsafe_allow_html=True)

    tab_vis, tab_sql = st.tabs(["ER Diagram", "SQL Schema"])

    with tab_vis:
        if st.session_state.last_mermaid:
            st.caption("Entity Relationship Diagram")
            st.components.v1.html(build_mermaid_html(st.session_state.last_mermaid, "Ghost Architect: Database Schema", st.session_state.last_sql or ""), height=900, scrolling=True)
        else:
            if st.session_state.last_sql:
                parsed_tables = parse_create_tables(st.session_state.last_sql)
                if parsed_tables:
                    render_schema_cards(parsed_tables)
            st.info("Mermaid diagram not available. Showing SQL below.")

    with tab_sql:
        if st.session_state.last_sql:
            st.code(st.session_state.last_sql, language="sql")
        else:
            st.code(st.session_state.get("last_raw_output", ""), language="text")

    if st.session_state.last_sql or st.session_state.last_mermaid:
        st.divider()
        dl_col1, dl_col2, dl_col3 = st.columns(3)
        if st.session_state.last_sql:
            dl_col1.download_button("Download SQL", data=st.session_state.last_sql, file_name="ghost_architect_schema.sql", mime="text/plain", use_container_width=True)
        if st.session_state.last_mermaid:
            dl_col2.download_button("Download Mermaid", data=st.session_state.last_mermaid, file_name="ghost_architect_schema.mmd", mime="text/plain", use_container_width=True)
        if st.session_state.last_sql and st.session_state.last_mermaid:
            report = f"# Ghost Architect — Database Schema\n\n## Design Decisions\n{st.session_state.get('last_explanation', 'N/A')}\n\n## ER Diagram\n```mermaid\n{st.session_state.last_mermaid}\n```\n\n## DDL\n```sql\n{st.session_state.last_sql}\n```\n"
            dl_col3.download_button("Download Report (.md)", data=report, file_name="ghost_architect_schema_report.md", mime="text/markdown", use_container_width=True)

    if not st.session_state.last_mermaid and not st.session_state.last_sql:
        parsed_tables = parse_create_tables(st.session_state.get("last_raw_output", ""))
        if parsed_tables:
            render_schema_cards(parsed_tables)


# ── Full-width diagram viewer ─────────────────────────────────────────────────
if st.session_state.get("last_mermaid"):
    st.markdown("---")
    col_left, col_right = st.columns([3, 1])
    with col_left:
        st.markdown(f"**📊 Full Diagram — {st.session_state.get('last_model', '')}**")
    with col_right:
        if st.button("🖼️ Toggle Full Size", key="toggle_full_diagram", use_container_width=True):
            st.session_state.show_full = not st.session_state.get("show_full", False)
    if st.session_state.get("show_full", False):
        st.components.v1.html(
            build_mermaid_html(
                st.session_state.last_mermaid,
                "Ghost Architect: Database Schema",
                st.session_state.get("last_sql", ""),
            ),
            height=1200,
            scrolling=True,
        )

# ── Footer ─────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="ghost-footer">
    <div class="links">
        <a href="https://github.com/HarshilMaks/ghost_architect_gemma3" target="_blank">GitHub</a>
        <a href="https://huggingface.co/harshilmaks/ghost-architect-gemma3-adapter" target="_blank">HuggingFace Model</a>
        <a href="https://aistudio.google.com" target="_blank">Gemini API</a>
    </div>
    <p>Ghost Architect · Gemini API · MIT</p>
</div>
""", unsafe_allow_html=True)
